lernanta/apps/users/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.views import password_reset
from django.views.generic.base import RedirectView

from users.decorators import anonymous_only
from users import forms

urlpatterns = patterns('',

# Login / auth urls
    url(r'^login/$', 'users.views.login',
        name='users_login'),
    url(r'^login/openid/$', 'users.views.login_openid',
        name='users_login_openid'),
    url(r'^login/openid/complete/$', 'users.views.login_openid_complete',
        name='users_login_openid_complete'),
    url(r'^logout/', 'users.views.logout',
        name='users_logout'),

# Reset password urls
    url(r'^forgot/$',
        anonymous_only(password_reset),
        {'template_name': 'users/forgot_password.html',
            'email_template_name': 'users/emails/forgot_password.txt',
            'password_reset_form': forms.PasswordResetForm},
        name='users_forgot_password'),

    url(r'^forgot/sent/$',
        'django.contrib.auth.views.password_reset_done',
        {'template_name': 'users/forgot_password_done.html'},
        name='users_forgot_password_done'),

    url(r'^forgot/(?P<uidb36>\w{1,13})/(?P<token>\w{1,13}-\w{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'users/forgot_password_confirm.html',
            'set_password_form': forms.SetPasswordForm},
        name='users_forgot_password_confirm'),

    url(r'^forgot/complete/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'users/forgot_password_complete.html'},
        name='users_forgot_password_complete'),

# Public pages
    url(r'^people/tag/(?P<tag_slug>[\w\-\. ]+)/$',
        'users.views.user_tagged_list', name="users_user_tagged_list"),
    url(r'^people/$', 'users.views.user_list',
        name='users_user_list'),

# Registration urls
    url(r'^register/$', 'users.views.register',
        name='users_register'),
    url(r'^register/openid/$', 'users.views.register_openid',
        name='users_register_openid'),
    url(r'^confirm/resend/$',
        'users.views.confirm_resend',
        name='users_confirm_resend'),
    url(r'^confirm/(?P<token>\w+)/(?P<username>[\w\-\. ]+)/$',
        'users.views.confirm_registration',
        name='users_confirm_registration'),
    url(r'^register/openid/complete/$', 'users.views.register_openid_complete',
        name='users_register_openid_complete'),

# Ajax handlers
    url(r'^ajax/check_username/$', 'users.views.check_username',
        name='users_check_username'),
    url(r'^ajax/following/$', 'users.views.following',
        name='users_followers'),

# Profile urls
    url(r'^(?P<username>[\w\-\. ]+)/$', 'users.views.profile_view',
        name='users_profile_view'),
    url(r'^profile/edit/$', 'users.views.profile_edit',
        name='users_profile_edit'),
    url(r'^profile/edit/badges/$', 'users.views.badges_manage',
        name='users_badges_manage'),
    url(r'^profile/edit/openids/$', 'users.views.profile_edit_openids',
        name='users_profile_edit_openids'),
    url(r'^profile/edit/openids/complete/$',
        'users.views.profile_edit_openids_complete',
        name='users_profile_edit_openids_complete'),
    url(r'^profile/edit/openids/delete/(?P<openid_pk>[\d]+)/$',
        'users.views.profile_edit_openids_delete',
        name='users_profile_edit_openids_delete'),
    url(r'^profile/edit/image/$', 'users.views.profile_edit_image',
        name='users_profile_edit_image'),
    url(r'^profile/edit/ajax_image/$', 'users.views.profile_edit_image_async',
        name='users_profile_edit_image_async'),
    url(r'^profile/link/(?P<counter>\d+)/up/$', 'users.views.link_index_up',
        name='link_index_up'),
    url(r'^profile/link/(?P<counter>\d+)/down/$', 'users.views.link_index_down',
        name='link_index_down'),
    url(r'^profile/edit/links/$', 'users.views.profile_edit_links',
        name='users_profile_edit_links'),
    url(r'^profile/edit/links/edit/(?P<link_id>[\d]+)/$',
        'users.views.profile_edit_links_edit',
        name='users_profile_edit_links_edit'),
    url(r'^profile/edit/links/delete/(?P<link>[\d]+)/$',
        'users.views.profile_edit_links_delete',
        name='users_profile_edit_links_delete'),
    url(r'^profile/edit/settings/$', 
        RedirectView.as_view(url='/profile/edit/notifications/')),
    url(r'^profile/edit/notifications/$', 'preferences.views.notifications',
        name='preferences_notifications'),
    url(r'^profile/edit/email/$', 'preferences.views.email',
        name='preferences_email'),
    url(r'^profile/edit/password/$', 'preferences.views.password',
        name='preferences_password'),
    url(r'^profile/delete/$', 'preferences.views.delete',
        name='preferences_delete'),
    url(r'^profile/create/$', 'users.views.profile_create',
        name='users_profile_create'),
)

lernanta/urls.py
from django.conf import settings
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/',     include('django.contrib.admindocs.urls')),
    (r'^admin/',         include(admin.site.urls)),
    (r'',                include('abuse.urls')),
    (r'^home/',          include('dashboard.urls')),
    (r'',                include('homepage.urls')),
    (r'^robots.txt$',    include('robots.urls')),
    (r'',                include('activity.urls')),
    (r'^statuses/',      include('statuses.urls')),
    (r'^groups/',        include('learn.urls')),
    (r'^groups/',        include('projects.urls')),
    (r'^courses/',       include('courses.urls')),
    (r'^schools/',       include('schools.urls')),
    (r'^relationships/', include('relationships.urls')),
    (r'^messages/',      include('drumbeatmail.urls')),
    (r'^pubsub/',        include('django_push.subscriber.urls')),
    (r'^richtext/',      include('richtext.urls')),
    (r'^pages/',         include('pages.urls')),
    (r'^search/',        include('search.urls')),
    (r'^chat/',          include('chat.urls')),
    (r'^comments/',      include('replies.urls')),
    (r'^badges/',        include('badges.urls')),
    (r'metrics/',        include('tracker.urls')),
    (r'reviews/',        include('reviews.urls')),
    (r'notifications/',  include('notifications.urls')),
    (r'api/',            include('api.urls')),
    (r'^oauth/',         include('oauthprovider.urls')),
    (r'^spam/',          include('spam.urls')),
    (r'',                include('users.urls')),
)

# for serving media when running a local dev server with DEBUG=True
media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
     {
         'document_root': settings.MEDIA_ROOT,
     }),
)

static_url = settings.STATIC_URL.lstrip('/').rstrip('/')
urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % static_url, 'django.views.static.serve',
     {
         'document_root': settings.STATIC_ROOT,
     }),
)

handler500 = 'drumbeat.views.server_error'
handler404 = 'drumbeat.views.page_not_found'

lernanta/apps/users/models.py
import logging
import datetime
import random
import string
import hashlib
import os


from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import smart_str
from django.utils.http import urlquote_plus
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext
from django.utils.safestring import mark_safe
from django.db.models.signals import post_save

from taggit.models import GenericTaggedItemBase, Tag
from south.modelsinspector import add_ignored_fields

from drumbeat import storage
from drumbeat.utils import get_partition_id, safe_filename
from drumbeat.models import ModelBase
from relationships.models import Relationship
from projects.models import Project, Participation
from notifications.models import send_notifications_i18n
from activity.schema import object_types
from users.managers import CategoryTaggableManager
from richtext.models import RichTextField
from tracker import statsd

import caching.base

log = logging.getLogger(__name__)

# To fix a South problem (Cannot freeze field 'users.userprofile.tags')
add_ignored_fields(["^users\.managers"])

GRAVATAR_TEMPLATE = ("https://secure.gravatar.com/avatar/%(gravatar_hash)s"
                     "?s=%(size)s&amp;d=%(default)s&amp;r=%(rating)s")


def determine_upload_path(instance, filename):
    chunk_size = 1000  # max files per directory
    return "images/profiles/%(partition)d/%(filename)s" % {
        'partition': get_partition_id(instance.pk, chunk_size),
        'filename': safe_filename(filename),
    }


def get_hexdigest(algorithm, salt, raw_password):
    """Generate password hash."""
    return hashlib.new(algorithm, smart_str(salt + raw_password)).hexdigest()


def create_password(algorithm, raw_password):
    """Create salted, hashed password."""
    salt = os.urandom(5).encode('hex')
    hsh = get_hexdigest(algorithm, salt, raw_password)
    return '$'.join((algorithm, salt, hsh))


class ProfileTag(Tag):
    CATEGORY_CHOICES = (
        ('skill', 'Skill'),
        ('interest', 'Interest'),
        ('desired_topic', 'Desired Topics'),
    )
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)


class TaggedProfile(GenericTaggedItemBase):
    tag = models.ForeignKey(
        ProfileTag, related_name="%(app_label)s_%(class)s_items")

    class Meta:
        verbose_name = "Tagged User Profile"
        verbose_name_plural = "Tagged User Profiles"


class UserProfileManager(caching.base.CachingManager):

    def get_popular(self, limit=0):
        users = Relationship.objects.values('target_user_id').annotate(
            models.Count('id')).filter(target_user__featured=False,
            target_user__deleted=False).order_by('-id__count')[:limit]
        user_ids = [u['target_user_id'] for u in users]
        return UserProfile.objects.filter(id__in=user_ids)


class UserProfile(ModelBase):
    """Each user gets a profile."""
    object_type = object_types['person']

    username = models.CharField(max_length=255, default='', unique=True)
    full_name = models.CharField(
        max_length=255, default='', null=True, blank=True)
    password = models.CharField(max_length=255, default='')
    email = models.EmailField(unique=True, null=True)
    bio = RichTextField(blank=True)
    image = models.ImageField(
        upload_to=determine_upload_path, default='', blank=True, null=True,
        storage=storage.ImageStorage())
    confirmation_code = models.CharField(
        max_length=255, default='', blank=True)
    location = models.CharField(max_length=255, blank=True, default='')
    featured = models.BooleanField()
    newsletter = models.BooleanField()
    discard_welcome = models.BooleanField(default=False)
    created_on = models.DateTimeField(
        auto_now_add=True, default=datetime.datetime.now)
    preflang = models.CharField(verbose_name='preferred language',
        max_length=16, choices=settings.SUPPORTED_LANGUAGES,
        default=settings.LANGUAGE_CODE)
    deleted = models.BooleanField(default=False)
    last_active = models.DateTimeField(null=True, blank=True)

    user = models.ForeignKey(User, null=True, editable=False, blank=True)

    tags = CategoryTaggableManager(through=TaggedProfile, blank=True)

    objects = UserProfileManager()

    class Meta:
        permissions = ( ('trusted_user', 'This is a trusted user'),)

    def __unicode__(self):
        if self.deleted:
            return ugettext('Anonym')
        return self.full_name or self.username

    def following(self, model=None):
        """
        Return a list of objects this user is following. All objects returned
        will be ```Project``` or ```UserProfile``` instances. Optionally filter
        by type by including a ```model``` parameter.
        """
        if (model == 'Project' or isinstance(model, Project) or
            model == Project):
            relationships = Relationship.objects.select_related(
                'target_project').filter(source=self, deleted=False).exclude(
                target_project__isnull=True)
            return [rel.target_project for rel in relationships
                    if not rel.target_project.archived]
        relationships = Relationship.objects.select_related(
            'target_user').filter(source=self,
            target_user__deleted=False, deleted=False).exclude(
            target_user__isnull=True)
        return [rel.target_user for rel in relationships]

    def followers(self):
        """Return a list of this users followers."""
        relationships = Relationship.objects.select_related(
            'source').filter(target_user=self, source__deleted=False,
            deleted=False)
        return [rel.source for rel in relationships]

    def is_following(self, model):
        """Determine whether this user is following ```model```."""
        return model in self.following(model=model)

    def get_current_projects(self, only_public=False):
        def to_dict(course):
            course_dict = {
                'id': course.slug,
                'title': course.name,
                'url': course.get_absolute_url(),
                'image_url': course.get_image_url(),
                'user_role': course.relation_text
            }
            return course_dict
            
        projects = self.following(model=Project)
        projects_organizing = []
        projects_participating = []
        projects_following = []
        count = len(projects)
        for project in projects:
            if only_public and project.not_listed:
                count -= 1
                continue
            is_challenge = (project.category == Project.CHALLENGE)
            if is_challenge:
                organizers = project.adopters()
                participants = project.non_adopter_participants()
            else:
                organizers = project.organizers()
                participants = project.non_organizer_participants()
            if organizers.filter(user=self).exists():
                if is_challenge:
                    project.relation_text = _('(adopted)')
                else:
                    project.relation_text = _('(organizing)')
                projects_organizing.append(to_dict(project))
            elif participants.filter(user=self).exists():
                project.relation_text = _('(participating)')
                projects_participating.append(to_dict(project))
            elif not is_challenge:
                project.relation_text = _('(following)')
                projects_following.append(to_dict(project))

        from courses.models import get_user_courses
        courses = get_user_courses(u'/uri/user/{0}'.format(self.username))
        for course in courses:
            if course["user_role"] == "ORGANIZER":
                course["user_role"] = _('(organizing)')
                projects_organizing.append(course)
            else:
                course["user_role"] = _('(participating)')
                projects_participating.append(course)

        data = {
            'organizing': projects_organizing,
            'participating': projects_participating,
            'following': projects_following,
            'count': count,
        }
        return data

    def get_past_projects(self, only_public=False):
        participations = Participation.objects.filter(user=self)
        current = participations.filter(project__archived=False,
            left_on__isnull=True)
        participations = participations.exclude(
            project__id__in=current.values('project_id'))
        past_projects = {}
        for p in participations:
            if p.project.slug in past_projects:
                past_projects[p.project.slug]['organizer'] |= p.organizing
            elif not only_public or not p.project.not_listed:
                past_projects[p.project.slug] = {
                    'title': p.project.name,
                    'url': p.project.get_absolute_url(),
                    'organizer': p.organizing,
                    'image_url': p.project.get_image_url(),
                }
        return past_projects.values()

    @models.permalink
    def get_absolute_url(self):
        username = 'people' if self.deleted else self.username
        return ('users_profile_view', (), {
            'username': username,
        })

    def email_confirmation_code(self, url, new_user=True):
        """Send a confirmation email to the user after registering."""
        subject_template = 'users/emails/registration_confirm_subject.txt'
        body_template = 'users/emails/registration_confirm.txt'
        context = {'confirmation_url': url, 'new_user': new_user}
        send_notifications_i18n([self], subject_template, body_template, 
            context, notification_category='account'
        )

    def image_or_default(self):
        """Return user profile image or a default."""

lernanta/templates/users/_profile_edit.html
  <div class="control-group field{% if profile_form.full_name.errors %} error{% endif %}">
    <label class="control-label" for="id_full_name">{{ _('Display Name') }}</label>
    <div class="controls">
      {{ profile_form.full_name }}
      {{ profile_form.full_name.errors }}
    </div>
  </div>
  <div class="control-group field{% if profile_form.location.errors %} error{% endif %}">
    <label class="control-label" for="id_location">{{ _('Location') }}</label>
      <div class="controls">
        {{ profile_form.location }}
        {{ profile_form.location.errors }}
      </div>
  </div>
  <div class="control-group field{% if profile_form.location.errors %} error{% endif %}">
    <label class="control-label" for="language">{{ _('Preferred Language') }}</label>
    <div class="controls">
      {{ profile_form.preflang}}
      {{ profile_form.preflang.errors }}
    </div>
  </div>
  <div class="control-group field{% if profile_form.bio.errors %} error{% endif %}">
    <label class="control-label" for="id_bio">{{ _('About Me') }}</label>
    <div class="controls">
      {{ profile_form.bio }}
      {{ profile_form.bio.errors }}
    </div>
  </div>
  <p>
    {{ _('Please describe your skills, interest, and the things you will want to learn, by providing a comma-separated list of tags.')}}
    <br />
    <br />
  </p>
  <div class="control-group field{% if profile_form.skill.errors %} error{% endif %}">
    <label class="control-label" for="id_skill">{{ _('Skilled in') }}</label>
    <div class="controls">
      {{ profile_form.skill }}
      {{ profile_form.skill.errors }}
    </div>
  </div>
  <div class="control-group field{% if profile_form.interest.errors %} error{% endif %}">
    <label class="control-label" for="id_interest">{{ _('Interested in') }}</label>
    <div class="controls">
      {{ profile_form.interest }}
      {{ profile_form.interest.errors }}
    </div>
  </div>
  <div class="control-group field{% if profile_form.desired_topic.errors %} error{% endif %}">
    <label class="control-label" for="id_desired_topic">{{ _('Want to learn more about') }}</label>
    <div class="controls">
      {{ profile_form.desired_topic }}
      {{ profile_form.desired_topic.errors }}
    </div>
  </div>

lernanta/templates/users/_profile_edit_image.html
<div class="row-fluid">
  
  <div class="row-fluid">
    <div class="span12">
      <div class="span2">
        <label for="id_image">{{ _('Current Profile Image') }}</label>
      </div>
      <div class="span10">
        <div class="field{% if profile_image_form.image.errors %} error{% endif %}">
          {% if profile.image %}
            <div class="alert alert-info">{{ _('Upload an image file from your computer to replace your current profile image:') }}</div>
          {% else %}
            <div class="alert alert-info">{{ _('Personalize your profile image by uploading an image file from your computer:') }}</div> 
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  
  <div class="row-fluid">
    <div class="span12">
      <div class="span2">
        <span class="picture-preview"><img class="member-picture" src="{{ profile.image_or_default }}" width="97" height="97" alt="Profile Image" /></span>
      </div>
      <div class="span10">
        <!-- Note the "Browse..." button comes from your OS so it will only appear in another language if you configure your PC for that language. -->
        <input type="file" name="image" id="id_image"/>
        <small class="hint block">{{ _('File Types: JPG, GIF or PNG only<br/> Max size: 700k <br/> Dimensions: 240x240 pixels') }}</small>
        {{ profile_image_form.image.errors }}  
      </div>
    </div>  
  </div>
  
</div>

<br clear="all" />

lernanta/templates/users/_profile_info.html
{% load l10n_tags %}
<div class="profile-wrapper">
  <div class="profile-top">

    <div class="row-fluid">
    <div class="span12">
    <div class="detailed-info">
    <ul class="">
      <li><a><span class="number">{{ users_followers|length }}</span>
      <span class="title">{{ _('Followers') }}</span></a></li>
      <li class="divider-vertical"></li>
      <li><a><span class="number">{{ users_following|length }}</span>
      <span class="title">{{ _('Followings') }}</span></a></li>
      <li class="divider-vertical"></li>
      <li><a><span class="number">{{ current_projects.count }}</span>
      <span class="title">{{ _('Courses') }}</span></a></li>
      <li class="divider-vertical"></li>
      <li><a><span class="number">{{ badges_count }}</span> <span class="title">{{ _('Badges') }}</span></a></li>
    </ul>
    </div>
    </div>
    </div>
    {% if current_projects.organizing or current_projects.participating or current_projects.following or past_projects or past_drupal_courses %}
    <div class="row-fluid">
    <div class="profile-courses">
      <h2>{{ _('Latest Courses') }} <small><a class="show-all-courses">{{ _('View All') }}</a></small></h2>
      <ul>
        {% for project in current_projects.organizing %}
          {% include "users/_project_image.html"%}
        {% endfor %}
        {% for project in current_projects.participating %}
          {% include "users/_project_image.html"%}
        {% endfor %}
        {% for project in current_projects.following %}
          {% include "users/_project_image.html"%}
        {% endfor %}
        {% for project in past_projects %}
          <li>
            <a href="{{ project.url }}" title="{{ project.title }} {% if project.organizer %}(organizer){% else%}(participant){% endif %}">
              <img src="{{ project.image_url }}" width="150" height="93" alt="{{ project.title }}"/>
            </a>
          </li>
          {% endfor %}
          {% for course in past_drupal_courses %}
            <li>
              <a href="{{ course.url }}" title="{{ course.name }} {% if course.organizer %}(organizer){% else%}(participant){% endif %}" target="_blank">
                <img src="{{ course.image_url }}" width="150" height="93" alt="{{ project.name }}"/>
              </a>
            </li>
          {% endfor %}
      </ul>
    </div>
    </div>
    {% endif %}

    {% if badges or pilot_badges %}
    <div class="row-fluid">
    <div class="profile-badges">
      <h2>
        {{ _('Latest Badges') }}
        <a href="{% locale_url users_badges_manage %}" title="{{ _('Share your badges') }}"><i class="icon-share icon-large"></i></a>
        <small><a class="show-all-badges">{{ _('View All') }}</a></small></h2>
      <ul>
        {% for badge in badges %}
          <li>
            <a href="{{ badge.evidence }}" title="{{ badge.name }} {% if badge.count > 1 %}(x{{ badge.count }}){% endif %}" target="_blank">
              <img src="{{ badge.image }}" width="70" height="70" alt="badge image"/>
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
    </div>
    {% endif %}
    <div class="row-fluid">
    <div class="profile-interests">
      {% if skills %}
      <h2>{{ _('My Skills') }}</h2>
      <ul class="tags skills">
        {% for skill in skills %}
          <li>
            <a href="{% locale_url users_user_tagged_list skill.slug %}" title="{{ _('View more with skills in ') }}{{ skill.name }}">
                {{ skill.name }}
            </a>
          </li>
        {% endfor %}
      </ul>
      {% endif %}
      {% if interests %}
      <h2>{{ _('My Interests') }}</h2>
      <ul class="tags interests">
        {% for interest in interests %}
          <li>
            <a href="{% locale_url users_user_tagged_list interest.slug %}" title="{{ _('View more interested in ') }}{{ interest.name }}">
              {{ interest.name }}
            </a>
          </li>
        {% endfor %}
      </ul>
      {% endif %}
      {% if desired_topics %}
      <h2>{{ _('What I want to learn more about') }}</h2>
      <ul class="tags interests">
        {% for topic in desired_topics %}
          <li>
            <a href="{% locale_url users_user_tagged_list topic.slug %}" title="{{ _('View more interested in learning more about ') }}{{ topic.name }}">
              {{ topic.name }}
            </a>
          </li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
    </div>
  </div>
</div>

lernanta/templates/users/forgot_password.html
{% extends "base.html" %}
{% load l10n_tags %}
{% block title %}{{ _('Forgot Your Password?') }}{% endblock %}
{% block bodyclasses %}signin{% endblock %}
{% block body %}
<section class="modal">
  <article>
    <h1>{{ _('Forgot your password?') }}</h1>
    <fieldset>
      <form action="{% locale_url users_forgot_password %}" method="post">
        {% csrf_token %}
        <div class="field{% if form.email.errors %} error{% endif %}">
          <label for="id_email">{{ _('Username or Email') }}</label>
          {{ form.email }}
          {{ form.email.errors }}
        </div>
        <p>
          <button type="submit">{{ _('Send') }}</button>
        </p>
      </form>
      <p>
        <a href="{% locale_url users_login %}">{{ _('Sign In') }}</a>
      </p>
    </fieldset>
  </article>
</section>
{% endblock %}

lernanta/templates/users/forgot_password_confirm.html
{% extends "base.html" %}

{% load l10n_tags %}

{% block title %}{{ _('Reset Password') }}{% endblock %}
{% block bodyclasses %}signin password_reset{% endblock %}
{% block body %}
<section class="modal">
  <article>
    <h1>{{ _('Reset Password') }}</h1>
    <fieldset>
      {% if validlink %}
      <form method="post" action="">
        {% csrf_token %}
        <p>
          <label for="id_new_password1">{{ _('New Password') }}</label>
          {{ form.new_password1 }}
          {{ form.new_password1.errors }}
        </p>
        <p>
          <label for="id_new_password2">{{ _('Confirm Password') }}</label>
          {{ form.new_password2 }}
          {{ form.new_password2.errors }}
        </p>
        <p>
          <button type="submit">{{ _('Update') }}</button>
        </p>
      </form>
      {% else %}
      <p>
        {{ _('Hmm, that does not appear to be a correct link.') }}
      </p>
      {% endif %}
    </fieldset>
  </article>
</section>
{% endblock %}

lernanta/templates/users/forgot_password_done.html
{% extends "base.html" %}

{% block title %}{{ _('Password Reset') }}{% endblock %}
{% block bodyclasses %}signin{% endblock %}
{% block body %}
<section class="modal">
  <article>
    <h1>{{ _('Password Reset') }}</h1>
    <fieldset>
      <p>{{ _('Instructions for resetting your password were sent to your email address.') }}</p>
    </fieldset>
  </article>
</section>
{% endblock %}

lernanta/templates/users/profile_form_base.html
{% extends "base.html" %}
{% load l10n_tags %}
{% block bodyclasses %}signin{% endblock %}

{% block body %}
<section class="modal">
  <article>
    <h1>{% block heading %}{% endblock %}</h1>
    <fieldset>
      <form action="{% block action %}{% endblock %}" method="post">
        {% csrf_token %}
        <div class="field{% if form.full_name.errors %} error{% endif %}">
          <label for="id_full_name">{{ _('Display Name') }}</label>
          {{ form.full_name }}
          {{ form.full_name.errors }}
          <small class="hint">{{ _('A name that will identify you to other users. This is optional.') }}</small>
        </div>
        <div id="username" class="field{% if form.username.errors %} error{% endif %}">
          <label for="id_username">{{ _('Username') }}</label>
          {{ form.username }}
          {{ form.username.errors }}
          <small class="hint">{{ _('Your public profile:') }} http://{{ domain }}/<b>{{ _('username') }}</b></small>
          <small class="hint" id="availability"></small>
        </div>
        {% block password_fields %}{% endblock %}
        <div class="field{% if form.email.errors %} error{% endif %}">
          <label for="id_email">{{ _('Email Address') }}</label>
          {{ form.email }}
          {{ form.email.errors }}
          <small class="hint">{{ _('Required to send you notifications about your P2PU account.') }}</small>
        </div>
        <div class="field{% if form.email_confirm.errors %} error{% endif %}">
          <label for="id_email_confirm">{{ _('Re-enter Email Address') }}</label>
          {{ form.email_confirm }}
          {{ form.email_confirm.errors }}
        </div>
        <div class="preflang">
          <label for="preflang">{{ _('Preferred Language') }}</label>
          {{ form.preflang }}
          {{ form.preflang.errors }}
        </div>
        <br>
        {% if settings.RECAPTCHA_PRIVATE_KEY %}
          <div class="field{% if form.recaptcha.errors %} error{% endif %}">
               <!-- Note: though recaptcha is localized the "Play sound again" and "Download sound as MP3" are in English -->
               {{ form.recaptcha }}
               {{ form.recaptcha.errors }}
          </div>
        {% else %}
          <p class="hint">
            {{ _('Welcome Robots, ReCaptcha has been disabled for your convenience. Spam at will.') }}
          </p>
        {% endif %}
        <p>
          {{ _('By creating an account on') }} {{ domain }}{{ _(', you accept our') }} <a href="{% locale_url static_page_show 'privacy' %}">{{ _('privacy guidelines') }}</a> , <a href="{% locale_url static_page_show 'license' %}">{{ _('license provisions') }}</a> {{ _('and') }} <a href="{% locale_url static_page_show 'terms-of-use' %}">{{ _('terms of use') }}</a>. {{ _('By default all content you create on this site is publicly viewable.') }}
        </p>
        <p class="submit">
          <button class="btn-olive" type="submit">{% block button_label %}{% endblock %}</button>          
          <a class="btn" href="{% locale_url splash %}" tabindex="5">{{ _('Cancel')}}</a>
          {% block openid_link %}{% endblock %}
        </p>
      </form>
    </fieldset>
  </article>
</section>
{% endblock %}

{% block js %}
  {% if settings.RECAPTCHA_PRIVATE_KEY %}
    <script type="text/javascript">
      var RecaptchaOptions = {
        theme : 'white',
        lang : '{{ _('en') }}'
      };
    </script>
    <script type="text/javascript" src="{{ settings.RECAPTCHA_URL }}"></script>
  {% endif %}
{% endblock %}