lernanta/apps/signups/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('signups.views',
    url(r'^$', 'show_signup', name='sign_up'),
    url(r'^edit/$', 'edit_signup', name='edit_signup'),
    url(r'^direct/$', 'direct_signup', name='direct_signup'),
    url(r'^direct/adopt/$', 'direct_signup_adopter',
        name='direct_signup_adopter'),
    url(r'^answer/$', 'answer_sign_up', name='sign_up_answer'),
    url(r'^answer/(?P<answer_id>\d+)/$',
        'show_signup_answer', name='show_signup_answer'),
    url(r'^answer/(?P<answer_id>\d+)/edit/$',
        'edit_answer_sign_up', name='sign_up_edit_answer'),
    url(r'^answer/(?P<answer_id>\d+)/delete/$',
        'delete_restore_signup_answer', name='delete_signup_answer'),
    url(r'^answer/(?P<answer_id>\d+)/restore/$',
        'delete_restore_signup_answer', name='restore_signup_answer'),
    url(r'^answer/(?P<answer_id>\d+)/accept_participant/$',
        'accept_sign_up', name='sign_up_accept_participant'),
    (r'^answer/(?P<answer_id>\d+)/accept_organizer/$',
        'accept_sign_up', {'as_organizer': True},
        'sign_up_accept_organizer'),
)

lernanta/urls.py
from django.conf import settings
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/',     include('django.contrib.admindocs.urls')),
    (r'^admin/',         include(admin.site.urls)),
    (r'',                include('abuse.urls')),
    (r'^home/',          include('dashboard.urls')),
    (r'',                include('homepage.urls')),
    (r'^robots.txt$',    include('robots.urls')),
    (r'',                include('activity.urls')),
    (r'^statuses/',      include('statuses.urls')),
    (r'^groups/',        include('learn.urls')),
    (r'^groups/',        include('projects.urls')),
    (r'^courses/',       include('courses.urls')),
    (r'^schools/',       include('schools.urls')),
    (r'^relationships/', include('relationships.urls')),
    (r'^messages/',      include('drumbeatmail.urls')),
    (r'^pubsub/',        include('django_push.subscriber.urls')),
    (r'^richtext/',      include('richtext.urls')),
    (r'^pages/',         include('pages.urls')),
    (r'^search/',        include('search.urls')),
    (r'^chat/',          include('chat.urls')),
    (r'^comments/',      include('replies.urls')),
    (r'^badges/',        include('badges.urls')),
    (r'metrics/',        include('tracker.urls')),
    (r'reviews/',        include('reviews.urls')),
    (r'notifications/',  include('notifications.urls')),
    (r'api/',            include('api.urls')),
    (r'^oauth/',         include('oauthprovider.urls')),
    (r'^spam/',          include('spam.urls')),
    (r'',                include('users.urls')),
)

# for serving media when running a local dev server with DEBUG=True
media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
     {
         'document_root': settings.MEDIA_ROOT,
     }),
)

static_url = settings.STATIC_URL.lstrip('/').rstrip('/')
urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % static_url, 'django.views.static.serve',
     {
         'document_root': settings.STATIC_ROOT,
     }),
)

handler500 = 'drumbeat.views.server_error'
handler404 = 'drumbeat.views.page_not_found'

lernanta/apps/signups/models.py
import datetime

from django.db import models
from django.contrib.sites.models import Site
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.template.loader import render_to_string
from django.contrib.contenttypes import generic
from django.db.models import Q
from django.conf import settings

from notifications.models import send_notifications_i18n
from drumbeat.models import ModelBase
from richtext.models import RichTextField
from activity.schema import object_types
from replies.models import PageComment
from projects.models import Participation


class Signup(ModelBase):
    project = models.ForeignKey('projects.Project', related_name='sign_up')
    public = RichTextField(config_name='rich', blank=True)
    between_participants = RichTextField(config_name='rich', blank=True)
    author = models.ForeignKey('users.UserProfile')

    MODERATED = 'moderated'
    NON_MODERATED = 'non-moderated'
    CLOSED = 'closed'
    STATUS_CHOICES = (
        (CLOSED, _('Closed signup')),
        (MODERATED, _('Moderated signup')),
        (NON_MODERATED, _('Non-moderated signup')),
    )
    status = models.CharField(max_length=30, choices=STATUS_CHOICES,
        default=CLOSED, null=True, blank=False)

    def __unicode__(self):
        return _('%s signup') % self.project

    @models.permalink
    def get_absolute_url(self):
        return ('sign_up', (), {
            'slug': self.project.slug,
        })

    @property
    def standard(self):
        return render_to_string('signups/sign_up_initial_content.html',
            {'project': self.project})

    def pending_answers(self):
        return self.answers.filter(accepted=False, deleted=False)

    def get_visible_answers(self, user):
        answers = self.answers.all()
        if user.is_authenticated():
            profile = user.get_profile()
            is_organizing = self.project.organizers().filter(
                user=profile).exists()
            if not is_organizing:
                answers = answers.filter(Q(accepted=True) | Q(author=profile))
        else:
            answers = answers.filter(accepted=True)
        return answers.order_by('-created_on')

    def get_page_for_answer(self, answer, user):
        answer_index = 0
        for visible_answer in self.get_visible_answers(user):
            if visible_answer.id == answer.id:
                break
            answer_index += 1
        items_per_page = settings.PAGINATION_DEFAULT_ITEMS_PER_PAGE
        return (answer_index / items_per_page) + 1

    def get_answer_url(self, answer, user):
        page = self.get_page_for_answer(answer, user)
        url = self.get_absolute_url()
        return url + '?pagination_page_number=%s#answer-%s' % (
            page, answer.id)

    def set_unmoderated_signup(self):
        self.status = self.NON_MODERATED
        self.save()

    def is_closed(self):
        return self.status == self.CLOSED


class SignupAnswer(ModelBase):
    object_type = object_types['comment']
    sign_up = models.ForeignKey('signups.Signup', related_name='answers')
    standard = RichTextField(config_name='rich', blank=False)
    public = RichTextField(config_name='rich', blank=True)
    between_participants = RichTextField(config_name='rich', blank=True)
    author = models.ForeignKey('users.UserProfile',
        related_name='sigup_answers')
    created_on = models.DateTimeField(
        auto_now_add=True, default=datetime.datetime.now)
    accepted = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)

    comments = generic.GenericRelation(PageComment,
        content_type_field='page_content_type',
        object_id_field='page_id')

    def __unicode__(self):
        return _("the signup answer of %(author)s at %(project)s") % {
            'author': self.author, 'project': self.project}

    @property
    def project(self):
        return self.sign_up.project

    @models.permalink
    def get_absolute_url(self):
        return ('show_signup_answer', (), {
            'slug': self.project.slug,
            'answer_id': self.id,
        })

    def can_edit(self, user):
        if user.is_authenticated():
            profile = user.get_profile()
            return (profile == self.author)
        else:
            return False

    def first_level_comments(self):
        return self.comments.filter(reply_to__isnull=True).order_by(
            'created_on')

    def has_visible_childs(self):
        return self.comments.filter(deleted=False).exists()

    def can_comment(self, user, reply_to=None):
        if user.is_authenticated():
            if self.accepted:
                return self.project.is_participating(user)
            else:
                is_organizing = self.project.is_organizing(user)
                profile = user.get_profile()
                return is_organizing or (profile == self.author)
        else:
            return False

    def get_comment_url(self, comment, user):
        page = self.sign_up.get_page_for_answer(self, user)
        url = self.sign_up.get_absolute_url()
        return url + '?pagination_page_number=%s#%s' % (
            page, comment.id)

    def comments_fire_activity(self):
        return False

    def comment_notification_recipients(self, comment):
        project = self.project
        recipients = {self.author.username: self.author}
        for organizer in project.organizers():
            recipients[organizer.user.username] = organizer.user
        while comment.reply_to:
            comment = comment.reply_to
            recipients[comment.author.username] = comment.author
        return recipients.values()

    def accept(self, as_organizer=False, reviewer=None):
        if not reviewer:
            reviewer = self.sign_up.author
        is_organizing = self.project.organizers().filter(
            user=self.author).exists()
        is_participating = self.project.participants().filter(
            user=self.author).exists()
        if not is_organizing and not is_participating:
            participation = Participation(project=self.project,
                user=self.author, organizing=as_organizer)
            participation.save()
        accept_content = render_to_string(
            "signups/accept_sign_up_comment.html",
            {'as_organizer': as_organizer})
        accept_comment = PageComment(content=accept_content,
            author=reviewer, page_object=self, scope_object=self.project)
        accept_comment.save()
        self.accepted = True
        self.save()


def send_new_signup_answer_notification(answer):
    recipients = answer.sign_up.project.organizers()
    subject_template = 'signups/emails/new_signup_answer_subject.txt'
    body_template = 'signups/emails/new_signup_answer.txt'
    context = {
        'answer': answer,
        'domain': Site.objects.get_current().domain,
    }
    profiles = [recipient.user for recipient in recipients]
    notification_category = u'course-signup.project-{0}'.format(
        answer.sign_up.project.slug
    )
    send_notifications_i18n(profiles, subject_template, body_template, context,
        notification_category=notification_category
    )


###########
# Signals #
###########


def post_save_answer(sender, **kwargs):
    instance = kwargs.get('instance', None)
    created = kwargs.get('created', False)
    is_answer = isinstance(instance, SignupAnswer)
    if created and is_answer:
        send_new_signup_answer_notification(instance)


post_save.connect(post_save_answer, sender=SignupAnswer,
    dispatch_uid='signups_post_save_answer')

lernanta/apps/signups/forms.py
from django import forms

from signups.models import Signup, SignupAnswer


class SignupForm(forms.ModelForm):

    class Meta:
        model = Signup
        fields = ('status', 'public', 'between_participants')


class SignupAnswerForm(forms.ModelForm):

    class Meta:
        model = SignupAnswer
        fields = ('standard', 'public', 'between_participants')

lernanta/templates/signups/accept_sign_up_comment.html
{% if as_organizer %}
  <p>{{ _('Welcome aboard! You are an organizer now.') }}</p>
{% else %}
  <p>{{ _('Welcome aboard! You are a participant now.') }}</p>
{% endif %}

lernanta/templates/signups/answer_sign_up.html
{% extends "signups/base.html" %}
{% load i18n %}
{% load l10n_tags %}
{% load embed %}
{% block css %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/course.css">
<!-- <link rel="stylesheet" href="{{ STATIC_URL }}css/batucada.css?v=1"> -->
{% endblock %}


{% block body %}

  <section class="well">
    <article>
      <h1>
        {% if create %}
          {{ _('New Answer') }}
        {% else %}
          {{ _('Edit answer') }}
        {% endif %}
      </h1>
      {% if preview %}
        <div id="posts">
          <div class="post-container">
            <img class="member-picture" width="54" height="54" src="{{ answer.author.image_or_default }}">
            <div class="post-contents">
              <div class="post-details">
                {{ _('[Preview]') }} {{ answer.author }} &nbsp; {{ answer.created_on }}
              </div>
              <div class="post-body">
	            <p><strong>{{ _('Bio:') }}</strong> {{ answer.author.bio|safe }}</p>
	            <p><strong>{{ _('Location:') }}</strong> {{ answer.author.location }}</p>
                <strong>{{ _('Standard Set Answer:') }}</strong>
                {{ answer.standard|embed|safe }}
                {% if answer.sign_up.public %}
                  <strong>{{ _('Public Set Answer:') }}</strong>
                  {{ answer.public|embed|safe }}
                {% endif %}
                {% if answer.sign_up.between_participants %}
                  <strong>{{ _('Between Participants Set Answer:') }}</strong>
                  {{ answer.between_participants|embed|safe }}
                {% endif %}
              </div>
            </div>
          </div>
          <br clear="both">
        </div>
      {% endif %}
      <br />
      <fieldset>
        {% if create %}
          <form class="form-horizontal" action="{% locale_url sign_up_answer slug=project.slug %}" method="post" enctype="multipart/form-data" data-url="{% locale_url users_profile_edit_image_async %}">
        {% else %}
          <form class="form-horizontal" action="{% locale_url sign_up_edit_answer slug=project.slug answer_id=answer.id %}" method="post" enctype="multipart/form-data" data-url="{% locale_url users_profile_edit_image_async %}">
        {% endif %}
          {% csrf_token %}
          <h2>{{ _('Profile') }}</h2>
          <p class="hint">{{ _('Your profile information is displayed with your signup answer. If you need, you can update the information of your profile bellow.') }}</p>
          <br /><br />     
          {% include "users/_profile_edit_image.html" %}
          {% include "users/_profile_edit.html" %}
          <h2>{{ _('Signup Questions') }}</h2>
          <p>{{ _('Please answer the following set(s) of questions if you want to become a participant or organizer.') }}</p>
          <h3>{{ _('Standard Set') }}</h3>
          <p>{{ _('This set of signup questions is common to all study groups, courses, ... in P2PU. The answers to these questions will be public once you get accepted.') }}</p>
          {{ sign_up.standard|embed|safe }}
          <br>
          <div class="field{% if form.standard.errors %} error alert alert-danger {% endif %}">
            {{ form.standard }}
            {{ form.standard.errors }}
          </div>
          {% if sign_up.public %}
            <h3>{{ _('Public Custom Set') }}</h3>
            <p>{% blocktrans with kind=project.kind|lower %}This set of signup questions is particular to this {{ kind }}. The answers to these questions will be public once you get accepted.{% endblocktrans %}</p>
            {{ sign_up.public|embed|safe }}
            <div class="field{% if form.public.errors %} error alert alert-danger {% endif %}">
              {{ form.public }}
              {{ form.public.errors }}
            </div>
          {% endif %}
          {% if sign_up.between_participants %}
            <h3>{{ _('Between Participants Custom Set') }}</h3>
            <p>{% blocktrans with kind=project.kind|lower %}This set of signup questions is particular to this {{ kind }}. The answers to these questions will be visible to all participants once you get accepted.{% endblocktrans %}</p>
            {{ sign_up.between_participants|embed|safe }}
            <div class="field{% if form.between_participants.errors %} error alert alert-danger{% endif %}">
              {{ form.between_participants }}
              {{ form.between_participants.errors }}
            </div>
          {% endif %}
          <p class="content_buttons">
            {% if create %}
              <a class="btn" href="{{ sign_up.get_absolute_url }}">
            {% else %}
              <a class="btn" href="{{ answer.get_absolute_url }}">
            {% endif %}
              {{ _('Cancel') }}
            </a>
            {% if create %}
              <button class="btn-primary" type="submit" value="{{ _('Post') }}">{{ _('Post') }}</button>
            {% else %}
              <button class="btn-primary" type="submit" value="{{ _('Save') }}">{{ _('Save') }}</button>
            {% endif %}
            <button type="submit" id="previewButton" name="show_preview" value="{{ _('Preview') }}">{{ _('Preview') }}</button>
          </p>
        </form>
      </fieldset>
    </article>
  </section>

{% endblock %}

lernanta/templates/signups/base.html
{% extends "projects/base.html" %}
{% load l10n_tags %}

{% block project_title %}{{ _('Sign-Up') }}{% endblock %}

{% block bodyid %}signup{% endblock %}

{% block project_breadcrumbs %}
  <span class="arrow">&rsaquo;</span>
  <a href="{{ sign_up.get_absolute_url }}">{{ _('Sign-Up') }}</a>
  {% block signup_breadcrumbs %}{% endblock %}
{% endblock %}

lernanta/templates/signups/delete_restore_answer.html
{% extends "signups/base.html" %}
{% load l10n_tags %}

{% block signup_breadcrumbs %}
  <span class="arrow">&rsaquo;</span>
  <a href="{{ answer.get_absolute_url }}">{{ answer.author }} {{ answer.created_on }}</a>
{% endblock %}

{% block body %}
<section class="modal">
  <article>
    <h1>
      {% if answer.deleted %}{{ _('Restore Answer:') }}{% else %}{{ _('Delete Answer:') }}{% endif %} {{ answer.author }} {{ answer.created_on }}
    </h1>
    <br />
    <fieldset>
    {% if answer.deleted %}
      <form action="{% locale_url restore_signup_answer slug=project.slug answer_id=answer.id %}" method="post">
    {% else %}
      <form action="{% locale_url delete_signup_answer slug=project.slug answer_id=answer.id %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% if answer.deleted %}
        <span class="hint block">{{ _('Are you sure you want to restore this answer?') }}</span>
      {% else %}
        <span class="hint block">{{ _('Are you sure you want to delete this answer?') }}</span>
      {% endif %}
      <p class="content_buttons">
        <a class="button" href="{% if answer.deleted %}{{ sign_up.get_absolute_url }}{% else %}{{ answer.get_absolute_url }}{%endif%}">
          {{ _('Cancel') }}
        </a>
        {% if answer.deleted %}
          <button type="submit" value="{{ _('Restore') }}">{{ _('Restore') }}</button>
        {% else %}
          <button type="submit" value="{{ _('Delete') }}">{{ _('Delete') }}</button>
        {% endif %}
      </p>
    </form>
    </fieldset>
  </article>
</section>
{% endblock %}

lernanta/templates/signups/edit_signup.html
{% extends "projects/project_edit.html" %}
{% load i18n %}
{% load l10n_tags %}
{% block bodyclasses %}project edit signup{% endblock %}

{% block links %}{% if school %}<link rel="stylesheet" href="{% locale_url schools_css slug=school.slug %}?v=1">{% endif %}{% endblock %}

{% block form %}
<fieldset id="project_edit_signup" class="project edit signup tabpane">
<form action="{% locale_url edit_signup slug=project.slug %}" method="post">
  {% csrf_token %}
  <div class="field status{% if form.public.errors %} error{% endif %}">
    <label for="id_status">{{ _('Sign-up Status') }}</label>
    <span class="hint block">{% blocktrans with kind=project.kind|lower %}To allow peers to signup to the {{kind}} change the signup status to either moderated of non-moderated signup.{% endblocktrans %}</span>
    {{ form.status }}
    {{ form.status.errors }}
  </div>
  <div class="field public{% if form.public.errors %} error{% endif %}">
    <label for="id_public">{{ _('Public Custom Set') }}</label>
    <span class="hint block">{% blocktrans with kind=project.kind|lower %}This set of signup questions is particular to this {{ kind }}. The answers to these questions will be public once you get accepted.{% endblocktrans %}</span>
    {{ form.public }}
    {{ form.public.errors }}
  </div>
  <div class="field{% if form.between_participants.errors %} error{% endif %}">
    <label for="id_between_participants">{{ _('Between Participants Custom Set') }}</label>
    <span class="hint block">{% blocktrans with kind=project.kind|lower %}This set of signup questions is particular to this {{ kind }}. The answers to these questions will be visible to all participants once you get accepted.{% endblocktrans %}</span>
    {{ form.between_participants }}
    {{ form.between_participants.errors }}
  </div>
  <p class="buttons">
    <a class="button" href="{{ project.get_absolute_url }}">{{ _('Cancel') }}</a>
    <button type="submit" value="{{ _('Save') }}">{{ _('Save') }}</button>
  </p>
</form>
</fieldset>
{% endblock %}

lernanta/templates/signups/sign_up.html
{% extends "signups/base.html" %}
{% load i18n %}
{% load l10n_tags %}
{% load embed %}
{% load project_tags %}
{% load comment_threads %}
{% load signup_tags %}
{% load pagination_tags %}

{% block breadcrumbs_actions %}
  {% if can_post_answer %}
    <a class="button" href="{% locale_url sign_up_answer slug=project.slug %}">{{ _('Post Answer') }}</a>
  {% endif %}
{% endblock %}

{% block body %}
{% sidebar %}
<div id="main" class="content_page">
<h1 class="school_header">{{ _('Sign-Up') }}</h1>
<hr />
<p>{{ _('Anyone can follow a') }} {{ project.kind|lower }} {{ _('on P2PU. Participating is the next level of engagement. The sign-up is a space where interested individuals can express their interest and background in the topic and commit to working with the rest of the participants. Please answer the following set(s) of questions if you want to become a participant or organizer.') }}</p>
<h3>{{ _('Standard Set') }}</h3>
<p>{{ _('This set of signup questions is common to all study groups, courses, ... in P2PU. The answers to these questions will be public once you get accepted.') }}</p>
{{ sign_up.standard|embed|safe }}

{% if sign_up.public %}
<br>
<h3>{{ _('Public Custom Set') }}</h3>
<p>{% blocktrans with kind=project.kind|lower %}This set of signup questions is particular to this {{ kind }}. The answers to these questions will be public once you get accepted.{% endblocktrans %}</p>
{{ sign_up.public|embed|safe }}
{% endif %}

{% if sign_up.between_participants %}
<br>
<h3>{{ _('Between Participants Custom Set') }}</h3>
<p>{% blocktrans with kind=project.kind|lower %}This set of signup questions is particular to this {{ kind }}. The answers to these questions will be visible to all participants once you get accepted.{% endblocktrans %}</p>
{{ sign_up.between_participants|embed|safe }}
{% endif %}

{% if pagination_current_page.object_list %}
<br>
<h1>{{ _('Answers') }}</h1>
{% if organizing %}<p>{{_('Pending Answers:')}} {{ pending_answers_count }}</p>{% endif %}
<br>
<ul id="posts">
{% for answer in pagination_current_page.object_list %}
  {% if answer.deleted %}
    {% if answer.has_visible_childs %}
      <li class="post-container deleted">
        <a name="answer-{{ answer.id }}"></a>
        {{ _('This answer was deleted.') }}
        {% if user|can_edit_signup_answer:answer %}
          <a class="action restore" href="{% locale_url restore_signup_answer slug=project.slug answer_id=answer.id %}">{{ _('Restore') }}</a>
        {% endif %}
      </li>
    {% endif %}
  {% else %}
    <li class="post-container">
      <a name="answer-{{ answer.id }}"></a>
      {% if user.is_authenticated %}
        <a class="action reply-to" href="{% locale_url page_comment scope_model='project' scope_app_label='projects' scope_pk=project.id page_model='signupanswer' page_app_label='signups' page_pk=answer.id %}">{{ _('Reply') }}</a>
        {% if user|can_edit_signup_answer:answer %}
          <a class="action delete" href="{% locale_url delete_signup_answer slug=project.slug answer_id=answer.id %}">{{ _('Delete') }}</a>
          <a class="action edit" href="{% locale_url sign_up_edit_answer slug=project.slug answer_id=answer.id %}">{{ _('Edit') }}</a>
        {% else %}
          <a class="report abuse action" href="{% locale_url drumbeat_abuse model="signupanswer" app_label="signups" pk=answer.id %}">{{ _('Report Abuse') }}</a>
        {% endif %}
      {% endif %}
      <a href="{{ answer.author.get_absolute_url }}">
        <img class="member-picture" width="54" height="54" src="{{ answer.author.image_or_default }}">
      </a>
      <div class="post-contents">
        <div class="post-details">
          <a href="{{ answer.author.get_absolute_url }}">{{ answer.author }}</a>
          &nbsp;
          <a href="{{ answer.get_absolute_url }}">{{ answer.created_on }}</a>
        </div>
        <div class="post-body">
	        <p><strong>{{ _('Bio:') }}</strong> {{ answer.author.bio|safe }}</p>
	        <p><strong>{{ _('Location:') }}</strong> {{ answer.author.location }}</p>
            <strong>{{ _('Standard Set Answer:') }}</strong>
            {{ answer.standard|embed|safe }}
            {% if answer.sign_up.public %}
              <strong>{{ _('Public Set Answer:') }}</strong>
              {{ answer.public|embed|safe }}
            {% endif %}
            {% if answer.sign_up.between_participants %}
              {% if participating or answer.author == user.get_profile %}
                <strong>{{ _('Between Participants Set Answer:') }}</strong>
                {{ answer.between_participants|embed|safe }}
              {% endif%}
            {% endif %}

          {% if organizing %}
            {% if not answer.accepted %}
              <form method="post" action="{% locale_url sign_up_accept_participant slug=project.slug answer_id=answer.id %}">
                {% csrf_token %}
                <button>{{ _('Add Participant') }}</button>
              </form>
              <form method="post" action="{% locale_url sign_up_accept_organizer slug=project.slug answer_id=answer.id %}">
                {% csrf_token %}
                <button>{{ _('Add Organizer') }}</button>
              </form>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </li>
  {% endif %}
  {% if participating or answer.author == user.get_profile %}
    <div id='extra-indent-post-replies'>
      {% with comments=answer.first_level_comments %}
        {% comment_threads %}
      {% endwith %}
    </div>
  {% endif %}
{% endfor %}
</ul>
{% with prefix='' page_url=sign_up.get_absolute_url %}
  {% pagination_links %}
{% endwith %}
{% endif %}
</div>
{% endblock %}

lernanta/templates/signups/sign_up_initial_content.html
{% load i18n %}
{% load l10n_tags %}
<ul>
	<li>{{ _('What made you interested in this topic?') }}</li>
	<li>{{ _('What do you hope to achieve by participating?') }}</li>
    <li>{% blocktrans with kind=project.kind|lower %}Are you interested in helping with the {{ kind }} organization?{% endblocktrans %}</li>
</ul>