lernanta/apps/content/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('content.views',
  url(r'^create/$', 'create_page', name='page_create'),
  url(r'^index/(?P<page_slug>[\w-]+)/up/$', 'page_index_up',
      name='page_index_up'),

  url(r'^index/(?P<page_slug>[\w-]+)/down/$', 'page_index_down',
      name='page_index_down'),
      
  url(r'^index/reorder/$', 'page_index_reorder',
      name='page_index_reorder'),
  url(r'^(?P<page_slug>[\w-]+)/$', 'show_page', name='page_show'),
      
  url(r'^(?P<page_slug>[\w-]+)/edit/$', 'edit_page', name='page_edit'),
  url(r'^(?P<page_slug>[\w-]+)/delete/$', 'delete_page', name='page_delete'),
  url(r'^(?P<page_slug>[\w-]+)/history/$', 'history_page',
      name='page_history'),
      
  url(r'^(?P<page_slug>[\w-]+)/history/(?P<version_id>\d+)/$',
      'version_page', name='page_version'),
      
  url(r'^(?P<page_slug>[\w-]+)/history/(?P<version_id>\d+)/restore/$',
      'restore_version', name='version_restore'),
      
  url(r'^(?P<page_slug>[\w-]+)/link_submit/$', 'link_submit',
      name='task_link_submit'),
)

lernanta/urls.py
from django.conf import settings
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/',     include('django.contrib.admindocs.urls')),
    (r'^admin/',         include(admin.site.urls)),
    (r'',                include('abuse.urls')),
    (r'^home/',          include('dashboard.urls')),
    (r'',                include('homepage.urls')),
    (r'^robots.txt$',    include('robots.urls')),
    (r'',                include('activity.urls')),
    (r'^statuses/',      include('statuses.urls')),
    (r'^groups/',        include('learn.urls')),
    (r'^groups/',        include('projects.urls')),
    (r'^courses/',       include('courses.urls')),
    (r'^schools/',       include('schools.urls')),
    (r'^relationships/', include('relationships.urls')),
    (r'^messages/',      include('drumbeatmail.urls')),
    (r'^pubsub/',        include('django_push.subscriber.urls')),
    (r'^richtext/',      include('richtext.urls')),
    (r'^pages/',         include('pages.urls')),
    (r'^search/',        include('search.urls')),
    (r'^chat/',          include('chat.urls')),
    (r'^comments/',      include('replies.urls')),
    (r'^badges/',        include('badges.urls')),
    (r'metrics/',        include('tracker.urls')),
    (r'reviews/',        include('reviews.urls')),
    (r'notifications/',  include('notifications.urls')),
    (r'api/',            include('api.urls')),
    (r'^oauth/',         include('oauthprovider.urls')),
    (r'^spam/',          include('spam.urls')),
    (r'',                include('users.urls')),
)

# for serving media when running a local dev server with DEBUG=True
media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
     {
         'document_root': settings.MEDIA_ROOT,
     }),
)

static_url = settings.STATIC_URL.lstrip('/').rstrip('/')
urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % static_url, 'django.views.static.serve',
     {
         'document_root': settings.STATIC_ROOT,
     }),
)

handler500 = 'drumbeat.views.server_error'
handler404 = 'drumbeat.views.page_not_found'

lernanta/apps/content/models.py
import logging
import datetime

from django.db import models
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
from django.db.models import Max
from django.contrib.sites.models import Site
from django.contrib.contenttypes import generic
from django.conf import settings

from drumbeat.models import ModelBase
from activity.models import Activity
from activity.schema import verbs, object_types
from notifications.models import send_notifications_i18n
from richtext.models import RichTextField
from replies.models import PageComment
from badges.models import Submission, Award


log = logging.getLogger(__name__)


class Page(ModelBase):
    """Placeholder model for pages."""
    object_type = object_types['article']

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=110)
    sub_header = models.CharField(max_length=150, blank=True, null=True)
    content = RichTextField(config_name='rich')
    author = models.ForeignKey('users.UserProfile', related_name='pages')
    last_update = models.DateTimeField(auto_now_add=True,
        default=datetime.datetime.now)
    project = models.ForeignKey('projects.Project', related_name='pages')
    listed = models.BooleanField(default=True)
    minor_update = models.BooleanField(default=True)
    collaborative = models.BooleanField(default=True)
    index = models.IntegerField()
    deleted = models.BooleanField(default=False)

    comments = generic.GenericRelation(PageComment,
        content_type_field='page_content_type',
        object_id_field='page_id')

    # Badges to which the user can submit their work to.
    # Used to facilitate both posting a comment to the task with
    # a link to the work they did on the task and apply for skills badges
    badges_to_apply = models.ManyToManyField('badges.Badge',
        null=True, blank=True, related_name='tasks_accepting_submissions')

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('page_show', (), {
            'slug': self.project.slug,
            'page_slug': self.slug,
        })

    def friendly_verb(self, verb):
        if verbs['post'] == verb:
            return _('added')

    def save(self):
        """Make sure each page has a unique url."""
        count = 1
        if not self.slug:
            slug = slugify(self.title)
            self.slug = slug
            while True:
                existing = Page.objects.filter(
                    project__slug=self.project.slug, slug=self.slug)
                if len(existing) == 0:
                    break
                self.slug = "%s-%s" % (slug, count + 1)
                count += 1
        if not self.index:
            if self.listed:
                max_index = Page.objects.filter(project=self.project,
                    listed=True).aggregate(Max('index'))['index__max']
                self.index = max_index + 1 if max_index else 1
            else:
                self.index = 0
        super(Page, self).save()

    def get_next_page(self):
        if self.listed and not self.deleted:
            try:
                return self.project.pages.filter(
                    deleted=False, index__gt=self.index,
                    listed=True).order_by('index')[0]
            except IndexError:
                pass
        return None

    def get_next_badge_can_apply(self, profile):
        next_badges = self.badges_to_apply.order_by('id')
        next_badges_can_apply = []
        for badge in next_badges:
            awarded = Award.objects.filter(user=profile,
                badge=badge).exists()
            applied = Submission.objects.filter(author=profile,
                badge=badge).exists()
            elegible = badge.is_eligible(profile)
            if not awarded and not applied and elegible:
                next_badges_can_apply.append(badge)
            if len(next_badges_can_apply) > 1:
                break
        next_badge = next_badges_can_apply[0] if next_badges_can_apply else None
        is_last_badge = not next_badges_can_apply[1:]
        return next_badge, is_last_badge

    def can_edit(self, user):
        if self.project.is_organizing(user):
            return True
        if self.collaborative:
            return self.project.is_participating(user)
        return False

    def first_level_comments(self):
        return self.comments.filter(reply_to__isnull=True).order_by(
            '-created_on')

    def can_comment(self, user, reply_to=None):
        conditions = [
            self.project.is_participating(user),
            not self.project.archived
        ]
        return all(conditions)

    def get_comment_url(self, comment, user):
        comment_index = 0
        abs_reply_to = comment.abs_reply_to or comment
        for first_level_comment in self.first_level_comments():
            if abs_reply_to.id == first_level_comment.id:
                break
            comment_index += 1
        items_per_page = settings.PAGINATION_DEFAULT_ITEMS_PER_PAGE
        page = (comment_index / items_per_page) + 1
        url = self.get_absolute_url()
        return url + '?pagination_page_number=%s#%s' % (
            page, comment.id)

    def comments_fire_activity(self):
        return True

    def comment_notification_recipients(self, comment):
        from users.models import UserProfile
        participants = self.project.participants()
        from_organizer = self.project.organizers().filter(
            user=comment.author).exists()
        if from_organizer:
            participants = participants.filter(
                no_organizers_content_updates=False)
        else:
            participants = participants.filter(
                no_participants_content_updates=False)
        return UserProfile.objects.filter(
            id__in=participants.values('user__id'))

    def recent_activity(self, min_count=2):
        comments = self.comments.filter(deleted=False)
        today = datetime.date.today()
        day = today.day
        month = today.month
        year = today.year
        # get today's commments count
        today_comments_count = comments.filter(created_on__day=day,
            created_on__month=month, created_on__year=year).count()
        if today_comments_count >= min_count:
            return today_comments_count, _('today')
        # get this week comments count
        week = today.isocalendar()[1]
        first_day = datetime.date(year, 1, 1)
        delta_days = first_day.isoweekday() - 1
        delta_weeks = week
        if year == first_day.isocalendar()[0]:
            delta_weeks -= 1
        week_start_delta = datetime.timedelta(days=-delta_days, weeks=delta_weeks)
        week_start = first_day + week_start_delta
        week_end_delta = datetime.timedelta(days=7-delta_days, weeks=delta_weeks)
        week_end = first_day + week_end_delta
        this_week_comments_count = comments.filter(created_on__gte=week_start,
            created_on__lt=week_end).count()
        if this_week_comments_count >= min_count:
            return this_week_comments_count, _('this week')
        # get this month comments count
        this_month_comments_count = comments.filter(created_on__month=month,
            created_on__year=year).count()
        return this_month_comments_count, _('this month')


class PageVersion(ModelBase):

    title = models.CharField(max_length=100)
    sub_header = models.CharField(max_length=150, blank=True, null=True)
    content = RichTextField(config_name='rich', blank=False)
    author = models.ForeignKey('users.UserProfile',
        related_name='page_versions')
    date = models.DateTimeField()
    page = models.ForeignKey('content.Page', related_name='page_versions')
    deleted = models.BooleanField(default=False)
    minor_update = models.BooleanField(default=True)

    @models.permalink
    def get_absolute_url(self):
        return ('page_version', (), {
            'slug': self.page.project.slug,
            'page_slug': self.page.slug,
            'version_id': self.id,
        })


def send_email_notification(instance):
    project = instance.project
    if not instance.listed:
        return
    recipients = project.participants()
    subject_template = 'content/emails/content_update_subject.txt'
    body_template = 'content/emails/content_update.txt'
    context = {
        'instance': instance,
        'project': project,
        'domain': Site.objects.get_current().domain,
    }
    from_organizer = project.organizers().filter(
        user=instance.author).exists()
    profiles = []
    for recipient in recipients:
        profile = recipient.user
        if instance.author != profile:
            profiles.append(profile)
    send_notifications_i18n(profiles, subject_template, body_template, context,
        notification_category=u'content-updated.project-{0}'.format(project.slug)
    )


###########
# Signals #
###########


def fire_activity(sender, **kwargs):
    instance = kwargs.get('instance', None)
    created = kwargs.get('created', False)
    is_page = isinstance(instance, Page)
    if created and is_page:
        send_email_notification(instance)
        # Fire activity.
        activity = Activity(actor=instance.author, verb=verbs['post'],
            target_object=instance, scope_object=instance.project)
        activity.save()
    elif (not created and is_page and not instance.minor_update \
          and not instance.deleted):
        activity = Activity(actor=instance.author, verb=verbs['update'],
            target_object=instance, scope_object=instance.project)
        activity.save()

post_save.connect(fire_activity, sender=Page,
    dispatch_uid='content_page_fire_activity')

lernanta/apps/content/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.template.defaultfilters import slugify

from projects.models import PerUserTaskCompletion
from badges.models import Submission

from content.models import Page


class OwnersPageForm(forms.ModelForm):

    """ field used to indicate that successful page creation should redirect here """
    next_url = forms.CharField(required=False,
        widget=forms.widgets.HiddenInput())
        
    class Meta:
        model = Page
        fields = ('title', 'sub_header', 'content',
            'collaborative', 'minor_update')

    def clean_title(self):
        data = self.cleaned_data.get('title')
        if len(slugify(data)) == 0:
            raise forms.ValidationError("Invalid title")
        return data


class PageForm(OwnersPageForm):

    class Meta(OwnersPageForm.Meta):
        exclude = ('collaborative',)


class NotListedPageForm(OwnersPageForm):

    class Meta(OwnersPageForm.Meta):
        exclude = ('title', 'collaborative',)


class OwnersNotListedPageForm(OwnersPageForm):

    class Meta(OwnersPageForm.Meta):
        exclude = ('title',)


class TaskLinkSubmitForm(forms.ModelForm):
    post_link = forms.BooleanField(required=False, initial=True)

    def __init__(self, show_badge_apply_option, *args, **kwargs):
        super(TaskLinkSubmitForm, self).__init__(*args, **kwargs)
        if show_badge_apply_option:
            self.fields['apply_for_badges'] = forms.BooleanField(required=False, initial=False)
        self.fields['url'].widget.attrs.update({'placeholder': _('Post a link to your work.')})
        self.fields['url'].required = True
        self.fields['url'].widget.is_required = True

    class Meta:
        model = PerUserTaskCompletion
        fields = ('url',)


class TaskBadgeApplyForm(forms.ModelForm):
    badge_slug = forms.SlugField(widget=forms.HiddenInput())

    class Meta:
        model = Submission
        fields = ('content',)

lernanta/templates/content/_post_link_comment.html
{% load l10n_tags %}
{{ _('This is a link to my work:') }} <a href="{{ url }}">{{ url }}</a>

lernanta/templates/content/_toggle_completion.html
{% load l10n_tags %}
{% if can_comment %}
  <hr />
  <form id="task-footer-toggle-task-completion-form" method='post' action='{% locale_url toggle_task_completion slug=page.project.slug page_slug=page.slug %}'>
    {% csrf_token %}
    {% if task_completion %}
      <p>
        {{ _('You\'ve marked this task as completed.') }}
        <button id="task-footer-toggle-task-completion-cancel-button">{{ _('Cancel') }}</button>
      </p>
    {% else %}
      <p>
        {{ _('Are you done with this task?') }}
        <button>{{ _('Yes, I\'m done') }}</button>
      </p>
    {% endif %}
  </form>

  {% if task_completion %}
    <div id="task-footer-after-completed">
      {% if task_link_submit_form %}
        <form id="task-footer-link-submit-form" method='post' action='{% locale_url task_link_submit slug=page.project.slug page_slug=page.slug %}'>
          {% csrf_token %}
          <div class="field{% if task_link_submit_form.url.errors %} error{% endif %}">
            {{ task_link_submit_form.url }}
            {{ task_link_submit_form.url.errors }}
          </div>
          <label for="id_post_link">
            {{ task_link_submit_form.post_link }}
            {{ _('Post to Discussion Wall') }}
          </label>
          {{ task_link_submit_form.post_link.errors }}
          {% if task_link_submit_form.apply_for_badges %}
            <label for="id_apply_for_badges">
              {{ task_link_submit_form.apply_for_badges }}
              {{ _('Submit this link to apply for the badges below') }} &#8595;
            </label>
            {{ task_link_submit_form.apply_for_badges.errors }}
          {% endif %}
          <br clear="both">
          <button type="submit">{{ _('Submit') }}</button>
        </form>
      {% else %}{% if task_badge_apply_form %}
        <form id="task-footer-badge-apply-form" method='post' action='{% locale_url task_link_submit slug=page.project.slug page_slug=page.slug %}'>
          {% csrf_token %}
          {{ task_badge_apply_form.badge_slug }}
          <div id="submission-edit-left">
            <img src="{{ next_badge.get_image_url }}" width="70" height="70" alt="{{ next_badge }}"/>
          </div>
          <div id="submission-edit-right">
            <h1>{{ _('Apply for this badge') }}</h1>
            <div id="badge-description-box">
              <h2>{{ next_badge }}</h2>
              <p>{{ next_badge.description }}</p>
              {% if next_badge.requirements %}
                <h3>{{ _('Requirements:') }}</h2> 
                {{ next_badge.requirements }}
              {% endif %}
            </div>
            <h2>{{_('Badge Application Form') }}</h2>
            <p>
              <label>{{ _('Url to the work you are submitting') }}</label>
              <a href="{{ task_completion.url }}" target="_blank">{{ task_completion.url }}</a>
            </p>
            <div class="field{% if task_badge_apply_form.content.errors %} error{% endif %}">
              <label for="id_content">{{ _('What did you learn? Why do you feel you deserve this badge?') }}</label>
              {{ task_badge_apply_form.content }}
              {{ task_badge_apply_form.content.errors }}
            </div>
            <button class="badge-apply-step-submit">{% if is_last_badge %}{{ _('Submit') }}{% else %}{{ _('Submit and move to the next badge application')}}{% endif %}</button>
          </div>
          <br clear="both">
        </form>
      {% else %}{% if next_page %}
        <a href={{ next_page.get_absolute_url }} title="{{ next_page.title }}">{{ _('Move on to next task') }}</a>
      {% endif %}{% endif %}{% endif %}
    </div>
  {% endif %}
{% endif %}

{% if badges_to_apply %}
  <div class="task-footer-badge-list">
    <h3>{{ _('Did you know that you can apply for these badges in this task?') }}</h3>
    <ul>
      {% for badge in badges_to_apply %}
        <li>
          <a href="{{ badge.get_absolute_url }}" class="badge" title="{{ badge|title }}">
            <img src="{{ badge.get_image_url }}" width="80" height="80" alt="{{ badge|title }}" />
            <span class="badge-name">{{ badge.name }}</span>
          </a>
          {% if badge.awarded %}
            <a class="task-badge-received-button" href="{{ badge.awarded.get_absolute_url }}">{{ _('Received!') }}</a>
          {% endif %}
          {% if badge.show_apply %}
            <a class="task-badge-apply-button" href="{% locale_url submission_create slug=badge.slug %}">{{ _('Apply') }}</a>
          {% endif %}
          {% if badge.applied %}
            <a class="task-badge-submitted-button" href="{{ badge.applied.get_absolute_url }}">{{ _('Submitted') }}</a>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

lernanta/templates/content/base_page_form.html
{% extends "projects/base.html" %}
{% load l10n_tags %}
{% load embed %}

{% block project_title %}{% if page %}{{ page.title }}{% endif %}{% endblock %}

{% block body %}

<section class="modal">
  <article>
    {% block page_form_title %}{% endblock %}
    <br />
    <fieldset>
    <form action="{% block page_form_url %}{% endblock %}" method="post" {% block form_extra_attributes %}{% endblock %}>
      {% csrf_token %}
      {{ form.next_url }}
      {% if preview %}
        <div class="preview">
            <h1 class="{% if page.collaborative %}collaborative{% endif %} school_header">
              {{ _('[Preview]') }} {{ page.title }}
            </h1>
            {% if is_challenge %}<br>{{ page.sub_header|default:"" }} {% endif %}
            <hr />
            <div id="task-body-preview">
              {{ page.content|embed|safe }}
            </div>
        </div>
        <br />
      {% endif %}
      {% block extra_fields %}{%endblock%}
      {% if form.title %}
        <div class="field{% if form.title.errors %} error{% endif %}">
          <label for="id_title">{{ _('Title') }}</label>
          <span class="hint block">{{ _('A good title is short and descriptive.') }}</span>
          {{ form.title }}
          {{ form.title.errors }}
        </div>
      {% endif %}
      {% if is_challenge %}
        <div class="field{% if form.sub_header.errors %} error{% endif %}">
          <label for="id_sub_header">{{ _('One sentence description') }}</label>
          <span class="hint block">{{ _('This description will be used as sub header below the task title.') }}</span>
          {{ form.sub_header }}
          {{ form.sub_header.errors }}
        </div>
      {% endif %}
      <div class="field{% if form.content.errors %} error{% endif %}">
        {{ form.content }}
        {{ form.content.errors }}
      </div>
      {% if form.collaborative %}
        <div class="field{% if form.collaborative.errors %} error{% endif %}">
          {{ form.collaborative }} {{ _('Collaborative work (editable by all the participants).') }}
          {{ form.collaborative.errors }}
        </div>
      {% endif %}
      <p class="content_buttons">
        {% block page_form_buttons %}{% endblock %}
        <button type="submit" id="previewButton" name="show_preview" value="{{ _('Preview') }}">{{ _('Preview') }}</button>
      </p>
    </form>
    </fieldset>
  </article>
</section>
{% endblock %}

lernanta/templates/content/confirm_delete_page.html
{% extends "projects/base.html" %}
{% load l10n_tags %}

{% block project_title %}{{ page.title }}{% endblock %}

{% block bodyid %}delete_page{% endblock %}


{% block project_breadcrumbs %}
  <span class="arrow">&rsaquo;</span>
  <a href="{% locale_url projects_task_list slug=project.slug %}">{{ _('Task List') }}</a>
  <span class="arrow">&rsaquo;</span>
  <a href="{{ page.get_absolute_url }}">{{ page.title }}</a>
{% endblock %}

{% block body %}
<section class="modal">
  <article>
    <h1>{{ _('Delete') }} {{ page.title }}</h1>
    <br />
    <fieldset>
    <form action="{% locale_url page_delete slug=page.project.slug page_slug=page.slug %}" method="post">
      {% csrf_token %}
      <span class="hint block">{{ _('Are you sure you want to delete this task?') }}</span>
      <p class="content_buttons">
        {% if next_page %}
          <div style="display:none"><input type="hidden" value="{{ next_page }}" name="next_page">
          </div>
          <a class="button" href="{{ next_page }}">{{ _('Cancel') }}</a>
        {% else %}
          <a class="button" href="{{ page.get_absolute_url }}">{{ _('Cancel') }}</a>
        {% endif %}
        <button type="submit" value="{{ _('Delete') }}">{{ _('Delete') }}</button>
      </p>
    </form>
    </fieldset>
  </article>
</section>
{% endblock %}

lernanta/templates/content/create_page.html
{% extends "content/base_page_form.html" %}
{% load l10n_tags %}
{% load embed %}

{% block project_title %}{{ _('Create Task') }}{% endblock %}

{% block bodyid %}create_page{% endblock %}

{% block project_breadcrumbs %}
  <span class="arrow">&rsaquo;</span>
  <a href="{% locale_url projects_task_list slug=project.slug %}">{{ _('Task List') }}</a>
{% endblock %}

{% block page_form_title %}
  <h1>{{ _('Create Task') }}</h1>
{% endblock %}

{% block extra_fields %}
  <span class="hint block">{{ _('Constructing a good task is crucial to the peer learning process. Tasks should have a clear goal in mind and should be sequential throughout the learning process. A task can be as big or as small and last as long as you like - it can be a planned discussion for one day, a piece of writing constructed over a week, a project that lasts for a few weeks, or a month-long endeavour that everyone works on.') }}</span>
{% endblock %}

{% block page_form_url %}
  {% locale_url page_create slug=project.slug %}
{% endblock %}

{% block page_form_buttons %}
  {% if form.next_url and form.next_url.value %}
  <a class="button" href="{{ form.next_url.value }}">
  {% else %}
  <a class="button" href="{{ project.get_absolute_url }}">
  {% endif %}
    {{ _('Cancel') }}
  </a>
  <button type="submit" value="{{ _('Create') }}">{{ _('Create') }}</button>
{% endblock %}

lernanta/templates/content/edit_page.html
{% extends "content/base_page_form.html" %}
{% load l10n_tags %}
{% load embed %}


{% block bodyid %}edit_page{% endblock %}


{% block project_breadcrumbs %}
  <span class="arrow">&rsaquo;</span>
  <a href="{% locale_url projects_task_list slug=project.slug %}">{{ _('Task List') }}</a>
  <span class="arrow">&rsaquo;</span>
  <a href="{{ page.get_absolute_url }}">{{ page.title }}</a>
{% endblock %}


{% block page_form_title %}
  <h1>[{{ _('Edit') }}] {{ page.title }}</h1>
{% endblock %}

{% block page_form_url %}
  {% locale_url page_edit slug=page.project.slug page_slug=page.slug %}
{% endblock %}

{% block extra_fields %}
  {% if page.listed %}
  <span class="hint block">{{ _('Constructing a good task is crucial to the peer learning process. Tasks should have a clear goal in mind and should be sequential throughout the learning process. A task can be as big or as small and last as long as you like - it can be a planned discussion for one day, a piece of writing constructed over a week, a project that lasts for a few weeks, or a month-long endeavour that everyone works on.') }}</span>
  {% endif %}
{% endblock %}

{% block page_form_buttons %}
  <div class="field{% if form.minor_update.errors %} error{% endif %}">
    {{ form.minor_update }} {{ _('Minor update (not posted to the wall).') }}
    {{ form.minor_update.errors }}
  </div>
  {% if form.next_url and form.next_url.value %}
  <a class="button" href="{{ form.next_url.value }}">
  {% else %}
  <a class="button" href="{{ page.get_absolute_url }}">
  {% endif %}
    {{ _('Cancel') }}
  </a>
  <button type="submit" value="{{ _('Save') }}">{{ _('Save') }}</button>
{% endblock %}

lernanta/templates/content/history_page.html
{% extends "projects/base.html" %}
{% load l10n_tags %}
{% load project_tags %}

{% block project_title %}{{ page.title }}{% endblock %}

{% block bodyid %}page{% endblock %}

{% block project_breadcrumbs %}
  <span class="arrow">&rsaquo;</span>
  <a href="{% locale_url projects_task_list slug=project.slug %}">{{ _('Task List') }}</a>
  <span class="arrow">&rsaquo;</span>      
  <a href="{{ page.get_absolute_url }}">{{ page.title }}</a>
  <span class="arrow">&rsaquo;</span>
  <a href="{% locale_url page_history slug=project.slug page_slug=page.slug %}">{{ _('History') }}</a>
{% endblock %}

{% block body %}
{% sidebar %}
<div id="main" class="content_page">
<h1>[{{ _('History') }}] {{ page.title }}</h1>
<hr />
<ul>
  {% if page.deleted %}
    <li>{{ _('deleted') }} &nbsp; {{ page.last_update }}
  {% else %}
    <li>{{ _('(current)') }} &nbsp; <a href="{{ page.get_absolute_url }}">{{ page.last_update }}</a>
  {% endif %}
    &nbsp;
    <a href="{{ page.author.get_absolute_url }}">{{ page.author }}</a></li>
  {% for version in versions %}
    {% if version.deleted %}
      <li>{{ _('deleted') }} &nbsp; {{ version.date }}
    {% else %}
      <li><a href="{{ version.get_absolute_url }}">{{ version.date }}</a>
    {% endif %}
    &nbsp;
    <a href="{{ version.author.get_absolute_url }}">{{ version.author }}</a></li>
  {% endfor %}
</ul>
</div>
{% endblock %}