lernanta/apps/reviews/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('',
  url(r'^$', 'reviews.views.show_new',
      name='reviews_show_new'),
  url(r'^reviewed/$', 'reviews.views.show_reviewed',
      name='reviews_show_reviewed'),
  url(r'^groups/(?P<slug>[\w-]+)/$', 'reviews.views.show_project_reviews',
      name='show_project_reviews'),
    url(r'^groups/(?P<slug>[\w-]+)/review/$', 'reviews.views.review_project',
      name='review_project'),
)

lernanta/urls.py
from django.conf import settings
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/',     include('django.contrib.admindocs.urls')),
    (r'^admin/',         include(admin.site.urls)),
    (r'',                include('abuse.urls')),
    (r'^home/',          include('dashboard.urls')),
    (r'',                include('homepage.urls')),
    (r'^robots.txt$',    include('robots.urls')),
    (r'',                include('activity.urls')),
    (r'^statuses/',      include('statuses.urls')),
    (r'^groups/',        include('learn.urls')),
    (r'^groups/',        include('projects.urls')),
    (r'^courses/',       include('courses.urls')),
    (r'^schools/',       include('schools.urls')),
    (r'^relationships/', include('relationships.urls')),
    (r'^messages/',      include('drumbeatmail.urls')),
    (r'^pubsub/',        include('django_push.subscriber.urls')),
    (r'^richtext/',      include('richtext.urls')),
    (r'^pages/',         include('pages.urls')),
    (r'^search/',        include('search.urls')),
    (r'^chat/',          include('chat.urls')),
    (r'^comments/',      include('replies.urls')),
    (r'^badges/',        include('badges.urls')),
    (r'metrics/',        include('tracker.urls')),
    (r'reviews/',        include('reviews.urls')),
    (r'notifications/',  include('notifications.urls')),
    (r'api/',            include('api.urls')),
    (r'^oauth/',         include('oauthprovider.urls')),
    (r'^spam/',          include('spam.urls')),
    (r'',                include('users.urls')),
)

# for serving media when running a local dev server with DEBUG=True
media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
     {
         'document_root': settings.MEDIA_ROOT,
     }),
)

static_url = settings.STATIC_URL.lstrip('/').rstrip('/')
urlpatterns += patterns('',
    (r'^%s/(?P<path>.*)$' % static_url, 'django.views.static.serve',
     {
         'document_root': settings.STATIC_ROOT,
     }),
)

handler500 = 'drumbeat.views.server_error'
handler404 = 'drumbeat.views.page_not_found'

lernanta/apps/reviews/models.py
import logging
import datetime

from django.db import models
from django.contrib.sites.models import Site

from drumbeat.models import ModelBase
from richtext.models import RichTextField
from notifications.models import send_notifications_i18n

log = logging.getLogger(__name__)


class Reviewer(ModelBase):
    user = models.ForeignKey('users.UserProfile')
    can_delete = models.BooleanField()
    can_feature = models.BooleanField()

    def __unicode__(self):
        return unicode(self.user)


class Review(ModelBase):

    project = models.ForeignKey('projects.Project', related_name='reviews')
    author = models.ForeignKey('users.UserProfile', related_name='reviews')
    accepted = models.BooleanField(default=False)
    mark_deleted = models.BooleanField(default=False)
    mark_featured = models.BooleanField(default=False)
    content = RichTextField(config_name='rich', blank=False)
    created_on = models.DateTimeField(auto_now_add=True,
        default=datetime.datetime.now)

    def __unicode__(self):
        return 'Review for %s' % self.project.name

    @models.permalink
    def get_absolute_url(self):
        return ('show_project_reviews', (), {
            'slug': self.project.slug,
        })

    def send_notifications_i18n(self):
        subject_template = 'reviews/emails/review_submitted_subject.txt'
        body_template = 'reviews/emails/review_submitted.txt'
        context = {
            'course': self.project.name,
            'reviewer': self.author.username,
            'review_text': self.content,
            'review_url': self.get_absolute_url(),
            'domain': Site.objects.get_current().domain, 
        }
        profiles = [recipient.user for recipient in self.project.organizers()]
        send_notifications_i18n(profiles, subject_template, body_template,
            context,
            notification_category=u'course-review.project-{0}'.format(self.project.slug)
        )

lernanta/apps/reviews/forms.py
from django import forms

from reviews.models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('accepted', 'content', 'mark_deleted', 'mark_featured')

lernanta/apps/reviews/views.py
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django import http
from django.utils.translation import ugettext as _

from pagination.views import get_pagination_context
from projects.models import Project
from users.decorators import login_required
from drumbeat import messages
from l10n.urlresolvers import reverse

from reviews.models import Review, Reviewer
from reviews.decorators import reviewer_required
from reviews.forms import ReviewForm


@login_required
@reviewer_required
def projects_reviews_list(request, toggled_reviewed=False):
    accepted_reviews = Review.objects.filter(
        accepted=True).values('project_id')
    new_projects = Project.objects.filter(under_development=False,
        archived=False, deleted=False, not_listed=False).exclude(
        id__in=accepted_reviews)
    reviewed_projects = Project.objects.filter(
        id__in=accepted_reviews)
    context = {
        'toggled_reviewed': toggled_reviewed,
        'show_new_page_url': reverse('reviews_show_new'),
        'show_reviewed_page_url': reverse('reviews_show_reviewed')
    }
    context.update(get_pagination_context(request, new_projects,
        24, prefix='new_'))
    context.update(get_pagination_context(request, reviewed_projects,
        24, prefix='reviewed_'))
    return render_to_response('reviews/projects_reviews_list.html',
        context, context_instance=RequestContext(request))


def show_new(request):
    return projects_reviews_list(request)


def show_reviewed(request):
    return projects_reviews_list(request, toggled_reviewed=True)


@login_required
@reviewer_required
def show_project_reviews(request, slug):
    project = get_object_or_404(Project, slug=slug)
    return render_to_response('reviews/show_project_reviews.html',
        {'project': project}, context_instance=RequestContext(request))


@login_required
@reviewer_required
def review_project(request, slug):
    project = get_object_or_404(Project, slug=slug)
    profile = request.user.get_profile()
    reviewer = Reviewer.objects.get(user=profile)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.project = project
            review.author = profile
            review.save()
            if reviewer.can_feature:
                project.community_featured = review.mark_featured
            if reviewer.can_delete:
                project.deleted = review.mark_deleted
            if reviewer.can_feature or reviewer.can_delete:
                project.save()
            review.send_notifications_i18n()
            messages.success(request, _('Review posted!'))
            return http.HttpResponseRedirect(review.get_absolute_url())
        else:
            messages.error(request, _('Please correct errors below.'))
    else:
        form = ReviewForm()
    context = {'form': form, 'project': project, 'reviewer': reviewer}
    return render_to_response('reviews/review_project.html',
        context, context_instance=RequestContext(request))

lernanta/templates/reviews/_project_review_action.html
{% load l10n_tags %}
{% if can_review %}
  <a class="button" href="{% locale_url review_project slug=project.slug %}">{{ _('Review') }}</a>
{% endif %}

lernanta/templates/reviews/_projects_reviews_list_item.html
{% load l10n_tags %}
<a href="{% locale_url show_project_reviews slug=project.slug %}">{{ project }}</a>
<a class="button" href="{% locale_url review_project slug=project.slug %}">{{ _('Review') }}</a>
<br>
<b>{{ _('Feedback Comments:') }}</b> {{ project.reviews.count }}

lernanta/templates/reviews/base.html
{% extends "base.html" %}
{% load l10n_tags %}

{% block title %}{% if project %}{{ project }} {% endif %}{{ _('Reviews')}} {% endblock %}

{% block bodyid %}project-reviews{% endblock %}

{% block breadcrumbs %}
  <span class="arrow">&rsaquo;</span>
  <a href="{% locale_url reviews_show_new %}">{{ _('Reviews') }}</a>
  {% if project %}
    <span class="arrow">&rsaquo;</span>
    <a href="{% locale_url show_project_reviews slug=project.slug %}">{{ project }}</a>
  {% endif %}
{% endblock %}

lernanta/templates/reviews/projects_reviews_list.html
{% extends "reviews/base.html" %}
{% load l10n_tags %}
{% load pagination_tags %}

{% block bodyclasses %}projects-reviews-list{% endblock %}

{% block body %}
  <div id="main">
    <div id="projects-reviews-list" class="{% if toggled_reviewed %}toggled-reviewed{% endif %}">
      <div id="projects-reviews-list-toggle">
        <input type="radio" id="radio1" name="radio" {% if not toggled_reviewed %}checked="checked"{% endif %} /><label for="radio1">{{ _('New Courses') }}</label>
        <input type="radio" id="radio2" name="radio" {% if toggled_reviewed %}checked="checked"{% endif %}/><label for="radio2">{{ _('Reviewed') }}</label>
      </div>
      <div id="new-projects-reviews-list">
        <ul>
          {% for project in new_pagination_current_page.object_list %}
            <li>
              {% include "reviews/_projects_reviews_list_item.html" %}
            </li>
          {% endfor %}
        </ul>
        {% with prefix='new_' page_url=show_new_page_url %}
          {% pagination_links %}
        {% endwith %}
      </div>
      <div id="reviewed-projects-reviews-list">
        <ul>
          {% for project in reviewed_pagination_current_page.object_list %}
            <li>
              {% include "reviews/_projects_reviews_list_item.html" %}
            </li>
          {% endfor %}
        </ul>
        {% with prefix='reviewed_' page_url=show_reviewed_page_url %}
          {% pagination_links %}
        {% endwith %}
      </div>
    </div>
  </div>
{% endblock %}

lernanta/templates/reviews/review_project.html
{% extends "reviews/base.html" %}
{% load l10n_tags %}
{% block bodyclasses %}review-project{% endblock %}

{% block body %} 
  <div id="main">
    <h1>{{ _('Review') }} <a href="{{ project.get_absolute_url }}" target="_blank">{{ project }}</a></h1>
    <br>
    <fieldset id="review-project">
      <form method="post" action="{% locale_url review_project slug=project.slug %}">
        {% csrf_token %}
        <div class="field{% if form.content.errors %} error{% endif %}">
          <label for="id_content">{{ _('Feedback') }}</label>
          {{ form.content }}
          {{ form.content.errors }}
        </div>
        <p>
          <label for="id_accepted">
            {{ form.accepted }}
            {{ _('Mark as Reviewed') }}
          </label>
          {{ form.accepted.errors }}
        </p>
        {% if reviewer.can_feature %}
          <p>
            <label for="id_mark_featured">
              {{ form.mark_featured }}
              {{ _('Feature as Community Pick') }}
            </label>
            {{ form.mark_featured.errors }}
          </p>
        {% endif %}
        {% if reviewer.can_delete %}
          <p>
            <label for="id_mark_deleted">
              {{ form.mark_deleted }}
              {{ _('Mark as Deleted (Spam)') }}
            </label>
            {{ form.mark_deleted.errors }}
          </p>
        {% endif %}
        <p class="buttons">
          <button type="submit" name="submit" value="{{ _('Submit') }}">{{ _('Submit') }}</button>
        </p>
      </form>
    </fieldset>
  </div>
{% endblock %}

lernanta/templates/reviews/show_project_reviews.html
{% extends "reviews/base.html" %}

{% load l10n_tags %}
{% load embed %}

{% block title %}{{ project }} {{ _('Reviews') }} {% endblock %}

{% block bodyclasses %}show-project-reviews{% endblock %}

{% block body %} 
  <div id="main">
    <h1><a href="{{ project.get_absolute_url }}" target='_blank'>{{ project }}</a> {{ _('Reviews') }} </h1>
    <ul id="posts">
      {% for review in project.reviews.all %}
        <li class="post-container">
          <p>{{ _('Review from') }} <a href="{{ review.author.get_absolute_url }}">{{ review.author }}</a> {{ _('on') }} {{ review.created_on }}</p>
          <div class="post-body assessment">
          {% if review.accepted %}<p>{{ _('Community Reviewed!') }}</p>{% endif %}
          {% if review.mark_deleted %}<p>{{ _('Deleted (Spam)!') }}</p>{% endif %}
          {% if review.mark_featured %}<p>{{ _('Featured as Community Pick!') }}</p>{% endif %}
          <p><b>{{ _('Feedback:') }}</b></p>
          {{ review.content|embed|safe }}
          </div>
        </li>
      {% endfor %}
    </ul>
    <br clear="both">
    <a href="{% locale_url review_project slug=project.slug %}" class="button">{{ _('Post New Review') }}</a>
  </div>
{% endblock %}